pub const GET_CAPABILITIES_PARAMETERS: u64 = 1;
pub const GET_CAPABILITIES_RETURNS: u64 = 2;
pub const READ_PARAMETERS: u64 = 3;
pub const READ_RETURNS: u64 = 4;
pub const WRITE_PARAMETERS: u64 = 5;


