pub const LIST_OBJECTS_PARAMETERS: u64 = 1;
pub const LIST_OBJECTS_RETURNS: u64 = 2;
pub const LOCK_OBJECT_PARAMETERS: u64 = 3;
pub const LOCK_OBJECT_RETURNS: u64 = 4;
pub const UNLOCK_OBJECT_PARAMETERS: u64 = 5;
pub const READ_OBJECT_PARAMETERS: u64 = 6;
pub const READ_OBJECT_RETURNS: u64 = 7;
pub const WRITE_OBJECT_PARAMETERS: u64 = 8;
pub const WATCH_OBJECT_PARAMETERS: u64 = 9;
pub const WATCH_OBJECT_RETURNS: u64 = 10;
pub const UNWATCH_OBJECT_PARAMETERS: u64 = 11;
pub const WATCHED_OBJECT_CHANGED_PARAMETERS: u64 = 12;


