pub const FILESYSTEM_DIRECTORY_LIST_CLIENT_MESSAGE: u64 = 1;
pub const FILESYSTEM_FILE_INFO_CLIENT_MESSAGE: u64 = 2;
pub const FILESYSTEM_FILE_READ_CLIENT_MESSAGE: u64 = 3;
pub const FILESYSTEM_FILE_COPY_CLIENT_MESSAGE: u64 = 4;
