pub const GET_CONSOLE_CAPABILITIES_PARAMETERS: u64 = 1;
pub const GET_CONSOLE_CAPABILITIES_RETURNS: u64 = 2;
pub const WRITE_CONSOLE_TEXT_PARAMETERS: u64 = 3;
pub const DRAW_IMAGE_PATCH_PARAMETERS: u64 = 4;
pub const DRAW_PIXEL_DEBUG_PARAMETERS: u64 = 5;
pub const KEY_PRESSED_PARAMETERS: u64 = 6;
pub const KEY_RELEASED_PARAMETERS: u64 = 7;
pub const CHARACTER_INPUT_PARAMETERS: u64 = 8;
pub const POINTER_MOVED_PARAMETERS: u64 = 9;
pub const POINTER_PRESSED_PARAMETERS: u64 = 10;
pub const POINTER_RELEASED_PARAMETERS: u64 = 11;
pub const SIZE_CHANGED_PARAMETERS: u64 = 12;


