pub const GET_CAPABILITIES_PARAMETERS: u64 = 1;
pub const GET_CAPABILITIES_RETURNS: u64 = 2;
pub const SET_TEXT_COLOR_PARAMETERS: u64 = 3;
pub const SAVE_TEXT_CURSOR_POSITION_PARAMETERS: u64 = 4;
pub const LOAD_TEXT_CURSOR_POSITION_PARAMETERS: u64 = 5;
pub const SET_TEXT_CURSOR_POSITION_PARAMETERS: u64 = 6;
pub const DRAW_IMAGE_PATCH_PARAMETERS: u64 = 7;
pub const WRITE_TEXT_PARAMETERS: u64 = 8;
pub const WRITE_OBJECTS_PARAMETERS: u64 = 9;
pub const DRAW_PIXEL_DEBUG_PARAMETERS: u64 = 10;
pub const KEY_PRESSED_PARAMETERS: u64 = 11;
pub const KEY_RELEASED_PARAMETERS: u64 = 12;
pub const CHARACTER_INPUT_PARAMETERS: u64 = 13;
pub const POINTER_MOVED_PARAMETERS: u64 = 14;
pub const POINTER_PRESSED_PARAMETERS: u64 = 15;
pub const POINTER_RELEASED_PARAMETERS: u64 = 16;
pub const SIZE_CHANGED_PARAMETERS: u64 = 17;


